name: Build firmware

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            git build-essential cmake ninja-build ccache \
            flex bison gperf python3 python3-pip python3-venv \
            libffi-dev libssl-dev dfu-util libusb-1.0-0 \
            pkg-config curl ca-certificates

      - name: Cache ESP-IDF tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.espressif
          key: ${{ runner.os }}-espressif-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-espressif-

      - name: Cache components checkout
        uses: actions/cache@v4
        with:
          path: |
            components
          key: ${{ runner.os }}-components-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-components-

      - name: Build firmware
        run: |
          make -j$(nproc)

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-binaries
          path: |
            firmware/*.bin
          if-no-files-found: error

